branch-defaults:
  master:
    environment: calendaronyourwebsi-env
global:
  application_name: Calendaronyourwebsite
  default_ec2_keyname: ken-key-pair
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.6
  default_region: us-east-1
  profile: null
  sc: git
